services:
  postgres:
    image: postgres:16
    container_name: organizze-postgres23
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: core2
      POSTGRES_USER: organizze
      POSTGRES_PASSWORD: organizze123
    network_mode: bridge
