CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    id_organizze INT NOT NULL,
    name VARCHAR(64) NOT NULL,
    group_id VARCHAR(64),
    essential BOOLEAN DEFAULT FALSE,
    uuid VARCHAR(64) NOT NULL,
    kind VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
